version: '3.8'
services:
    fpm:
        build:
            context: .
            dockerfile: ./fpm/Dockerfile
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ../users/:/var/www/test-system/users
            - ../quiz/:/var/www/test-system/quiz
            - ../web/:/var/www/test-system/web
        depends_on:
            - db
    webserver:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - "8050:80"
            - "443:443"
        working_dir: /var/www
        volumes:
            - ../users/:/var/www/test-system/users
            - ../quiz/:/var/www/test-system/quiz
            - ../web/:/var/www/test-system/web
            - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - fpm
    db:
        image: mysql:latest
        restart: unless-stopped
        tty: true
        ports:
            - "3305:3306"
        environment:
            MYSQL_DATABASE: quiz
            MYSQL_ROOT_PASSWORD: root
