version: '3.8'
services:
  fpm:
    build:
      context: .
      dockerfile: ./fpm/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ../users/:/var/www/test-system/users
      - ../quiz/:/var/www/test-system/quiz
      - ../web/:/var/www/test-system/web
      - ../common/:/var/www/test-system/common
    depends_on:
      - quiz_db
      - quiz_user_db
  webserver:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "8050:80"
      - "443:443"
    expose:
      - 8050
    working_dir: /var/www
    volumes:
      - ../users/:/var/www/test-system/users
      - ../quiz/:/var/www/test-system/quiz
      - ../web/:/var/www/test-system/web
      - ../common/:/var/www/test-system/common
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm
  quiz_db:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - "3305:3306"
    volumes:
      - ./db/quiz_db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
  quiz_user_db:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./db/quiz_user_db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
  migraion_db:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./db/migration_db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root